#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[0] = LAYOUT(

KC_ESC, KC_TAB, ALGR_T(KC_CAPS), ALT_T(KC_NUBS), SFT_T(KC_SPC), TG(2), KC_O, KC_I, KC_U, KC_Y,
KC_W, KC_Q, KC_A, KC_Z, CTL_T(KC_BSPC), KC_GRV , KC_P, KC_L, KC_K, KC_J,
KC_E, KC_S, KC_X, KC_LCMD, LT(3, KC_ENT), KC_MINS, KC_SCLN, KC_DOT, KC_COMMA, KC_M,
KC_R, KC_D, KC_C, LT(2, KC_HOME), KC_B, KC_EQL, KC_SLSH, KC_INT1, LT(1, KC_END), KC_RGHT,
KC_T, KC_F, KC_V, LT(4, KC_DEL), KC_G, KC_DOWN, KC_LEFT, KC_UP, KC_N, KC_H

),

[1] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_4), LSFT(KC_3), KC_BSLS, KC_RBRC,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRV , KC_LBRC , LSFT(KC_6), LSFT(KC_5), LSFT(KC_0),
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_QUOT , LSFT(KC_8), LSFT(KC_7), LSFT(KC_2),
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_EQL, KC_NUBS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_1), LSFT(KC_9)

),
	
[2] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_9, KC_8, KC_7, KC_TRNS,
KC_7, KC_TRNS, KC_0, KC_TRNS, KC_TRNS, KC_PMNS, KC_PPLS, KC_6, KC_5, KC_4,
KC_8, KC_4, KC_1, KC_TRNS, KC_TRNS, KC_PSLS, KC_PAST, KC_3, KC_2, KC_1,
KC_9, KC_5, KC_2, KC_TRNS, KC_DOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_TRNS, KC_6, KC_3, KC_TRNS, KC_COMMA, KC_DOT, KC_TRNS, KC_COMMA, KC_0, KC_TRNS

),

[3] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F7, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F8, KC_F4, KC_F1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F9, KC_F5, KC_F2, KC_TRNS, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F10, KC_F6, KC_F3, KC_TRNS, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

),

[4] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_UP, KC_LEFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_TRNS, KC_DOWN, KC_TRNS, KC_TRNS, KC_TRNS, KC_BRK, KC_TRNS, KC_TRNS, KC_TRNS, KC_END,
KC_TRNS, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGDN, KC_HOME, KC_PGUP, KC_TRNS, KC_TRNS

)
};
