#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[0] = LAYOUT(

KC_ESC, KC_TAB, ALGR_T(KC_CAPS), ALT_T(KC_NUBS), SFT_T(KC_SPC), KC_Y, KC_J, KC_M, KC_RGHT, KC_H,
KC_W, KC_Q, KC_A, KC_Z, CTL_T(KC_BSPC), KC_U, KC_K, KC_COMMA, LT(1, KC_END), KC_N,
KC_E, KC_S, KC_X, KC_LCMD, KC_ENT, KC_I, KC_L, KC_DOT, KC_INT1, KC_UP,
KC_R, KC_D, KC_C, LT(2, KC_HOME), KC_B, KC_O, KC_P, KC_SCLN, KC_SLSH, KC_LEFT,
KC_T, KC_F, KC_V, LT(3, KC_DEL), KC_G, TG(2), KC_GRV , KC_MINS, KC_EQL, KC_DOWN

),

[1] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RBRC, LSFT(KC_0), LSFT(KC_2), KC_TRNS, LSFT(KC_9),
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSLS, LSFT(KC_5), LSFT(KC_7), KC_TRNS, LSFT(KC_1),
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_3), LSFT(KC_6), LSFT(KC_8), KC_TRNS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LSFT(KC_4), KC_LBRC , KC_QUOT , KC_NUBS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRV , KC_MINS, KC_EQL, KC_TRNS

),
	
[2] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_4, KC_1, KC_TRNS, KC_TRNS,
KC_7, KC_TRNS, KC_0, KC_TRNS, KC_TRNS, KC_7, KC_5, KC_2, KC_TRNS, KC_0,
KC_8, KC_4, KC_1, KC_TRNS, KC_TRNS, KC_8, KC_6, KC_3, KC_TRNS, KC_COMMA,
KC_9, KC_5, KC_2, KC_TRNS, KC_DOT, KC_9, KC_PPLS, KC_PAST, KC_TRNS, KC_TRNS,
KC_TRNS, KC_6, KC_3, KC_TRNS, KC_COMMA, KC_TRNS, KC_PMNS, KC_PSLS, KC_TRNS, KC_DOT

),

[3] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F7, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F8, KC_F4, KC_F1, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F9, KC_F5, KC_F2, KC_TRNS, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_F10, KC_F6, KC_F3, KC_TRNS, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

),

[4] = LAYOUT(

KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_END, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INS, KC_PSCR, KC_BRK, KC_PGDN

)
};
